"""
Utilities for detecting autodoc-generated content.

Provides a canonical implementation for detecting whether a page was
generated by Bengal's autodoc system. This consolidates duplicate
implementations found in:
- bengal/analysis/knowledge_graph.py (_is_autodoc_page)
- bengal/health/validators/directives.py (_is_autodoc_file)

See RFC: plan/active/rfc-code-quality-improvements.md
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from bengal.core.page import Page


def is_autodoc_page(page: Page | Any) -> bool:
    """
    Check if a page is autodoc-generated.

    Autodoc pages are identified by multiple signals:

    **Frontmatter Indicators**:
    - Type starting with "python-" (python-module, python-class, etc.)
    - Type "cli-reference" or "api-reference"
    - Presence of "source_file" field
    - Generator metadata "bengal-autodoc"
    - Presence of "_api_doc" marker

    **Content Indicators**:
    - Content containing "Generated by Bengal autodoc"
    - Content containing "Generated by Bengal"

    **Path Indicators**:
    - Source path contains "/api/"
    - Source path ends with "/api"

    Args:
        page: Page object to check. Can be a Page, PageProxy, or any
              object with metadata/frontmatter and content attributes.

    Returns:
        True if page is autodoc-generated

    Example:
        >>> from bengal.utils.autodoc import is_autodoc_page
        >>> if is_autodoc_page(page):
        ...     # Skip autodoc pages in analysis
        ...     continue
    """
    # Check frontmatter/metadata for autodoc indicators
    # Try both 'metadata' (Page) and 'frontmatter' (some validators use this)
    metadata = getattr(page, "metadata", None) or getattr(page, "frontmatter", {})

    if isinstance(metadata, dict):
        page_type = metadata.get("type", "")

        # Check type-based indicators
        if (
            page_type.startswith("python-")  # python-module, python-class, etc.
            or page_type in ("cli-reference", "api-reference")
            or "source_file" in metadata  # Generated from source file
            or metadata.get("generator") == "bengal-autodoc"  # Explicit generator marker
            or metadata.get("_api_doc") is not None  # Internal API doc marker
        ):
            return True

    # Check source path for API directory patterns
    source_path = getattr(page, "source_path", None)
    if source_path:
        path_str = str(source_path)
        if "/api/" in path_str or path_str.endswith("/api"):
            return True

    # Check content for autodoc footer
    content = getattr(page, "content", "")
    if isinstance(content, str):
        if "Generated by Bengal autodoc" in content or "Generated by Bengal" in content:
            return True

    return False

