"""
Tests for FontCSSGenerator.

Tests CSS generation for @font-face rules and CSS custom properties.
"""

import pytest

from bengal.fonts.downloader import FontVariant
from bengal.fonts.generator import FontCSSGenerator


class TestFontCSSGenerator:
    """Tests for FontCSSGenerator.generate() method."""

    @pytest.fixture
    def generator(self) -> FontCSSGenerator:
        """Create a generator instance."""
        return FontCSSGenerator()

    def test_returns_empty_string_for_empty_mapping(self, generator: FontCSSGenerator) -> None:
        """Returns empty string when no fonts provided."""
        result = generator.generate({})
        assert result == ""

    def test_generates_minimal_css_for_empty_variants(self, generator: FontCSSGenerator) -> None:
        """Generates header and empty :root when all variant lists are empty."""
        result = generator.generate({"primary": []})
        # Still outputs structure, just no @font-face rules or variables
        assert "/* Auto-generated by Bengal Font Helper */" in result
        assert "@font-face" not in result
        assert "--font-primary" not in result

    def test_generates_font_face_rule(self, generator: FontCSSGenerator) -> None:
        """Generates @font-face rule for a single variant."""
        variants = {
            "primary": [
                FontVariant("Inter", 400, "normal", "https://fonts.gstatic.com/inter.woff2")
            ]
        }
        result = generator.generate(variants)

        assert "@font-face {" in result
        assert "font-family: 'Inter';" in result
        assert "font-weight: 400;" in result
        assert "font-style: normal;" in result
        assert "font-display: swap;" in result
        assert "url('fonts/inter-400.woff2')" in result
        assert "format('woff2')" in result

    def test_generates_multiple_font_face_rules(self, generator: FontCSSGenerator) -> None:
        """Generates @font-face rules for multiple weights."""
        variants = {
            "primary": [
                FontVariant("Inter", 400, "normal", "https://fonts.gstatic.com/inter.woff2"),
                FontVariant("Inter", 700, "normal", "https://fonts.gstatic.com/inter.woff2"),
            ]
        }
        result = generator.generate(variants)

        # Should have two @font-face blocks
        assert result.count("@font-face {") == 2
        assert "font-weight: 400;" in result
        assert "font-weight: 700;" in result

    def test_generates_css_custom_properties(self, generator: FontCSSGenerator) -> None:
        """Generates CSS custom properties for font roles."""
        variants = {
            "primary": [
                FontVariant("Inter", 400, "normal", "https://fonts.gstatic.com/inter.woff2")
            ],
            "heading": [
                FontVariant("Playfair Display", 700, "normal", "https://fonts.gstatic.com/p.woff2")
            ],
        }
        result = generator.generate(variants)

        assert ":root {" in result
        assert "--font-primary: 'Inter';" in result
        assert "--font-heading: 'Playfair Display';" in result

    def test_handles_italic_style(self, generator: FontCSSGenerator) -> None:
        """Generates correct font-style for italic variants."""
        variants = {
            "primary": [
                FontVariant("Inter", 400, "italic", "https://fonts.gstatic.com/inter.woff2")
            ]
        }
        result = generator.generate(variants)

        assert "font-style: italic;" in result
        assert "url('fonts/inter-400-italic.woff2')" in result

    def test_handles_ttf_format(self, generator: FontCSSGenerator) -> None:
        """Detects TTF format and uses truetype format string."""
        variants = {
            "primary": [
                FontVariant("Outfit", 400, "normal", "https://fonts.gstatic.com/outfit.ttf")
            ]
        }
        result = generator.generate(variants)

        assert "url('fonts/outfit-400.ttf')" in result
        assert "format('truetype')" in result

    def test_custom_font_path_prefix(self, generator: FontCSSGenerator) -> None:
        """Uses custom font path prefix."""
        variants = {
            "primary": [
                FontVariant("Inter", 400, "normal", "https://fonts.gstatic.com/inter.woff2")
            ]
        }
        result = generator.generate(variants, font_path_prefix="assets/webfonts")

        assert "url('assets/webfonts/inter-400.woff2')" in result

    def test_includes_header_comment(self, generator: FontCSSGenerator) -> None:
        """Generated CSS includes header comment."""
        variants = {
            "primary": [
                FontVariant("Inter", 400, "normal", "https://fonts.gstatic.com/inter.woff2")
            ]
        }
        result = generator.generate(variants)

        assert "/* Auto-generated by Bengal Font Helper */" in result
        assert "/* See bengal.toml [fonts] section */" in result

    def test_includes_family_comment(self, generator: FontCSSGenerator) -> None:
        """Generated CSS includes family name comment."""
        variants = {
            "primary": [
                FontVariant("Playfair Display", 400, "normal", "https://fonts.gstatic.com/p.woff2")
            ]
        }
        result = generator.generate(variants)

        assert "/* Playfair Display */" in result

    def test_skips_empty_variant_lists(self, generator: FontCSSGenerator) -> None:
        """Skips font roles with empty variant lists."""
        variants = {
            "primary": [
                FontVariant("Inter", 400, "normal", "https://fonts.gstatic.com/inter.woff2")
            ],
            "heading": [],  # Empty - should be skipped
        }
        result = generator.generate(variants)

        # Should only have one @font-face and one CSS variable
        assert result.count("@font-face {") == 1
        assert "--font-primary: 'Inter';" in result
        assert "--font-heading" not in result
