[site]
title = "ᓚᘏᗢ Bengal SSG"
baseurl = ""
theme = "default"

[build]
output_dir = "public"
parallel = true

[assets]
minify = true
fingerprint = true

[features]
syntax_highlighting = true
search = true
analytics = false


# Autodoc Configuration - Generate Bengal API documentation
[autodoc.python]
enabled = true
source_dirs = ["../bengal"] # Document the main Bengal package
output_dir = "content/api"  # Generated API docs go here
docstring_style = "auto"    # Auto-detect docstring format

# Exclude test and cache files
exclude = [
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/migrations/*",
    "*/.pytest_cache/*",
]

# Member visibility
include_private = false # Skip _private methods
include_special = false # Skip __special__ methods


[autodoc.cli]
enabled = true
app_module = "bengal.cli:main"
framework = "click"
output_dir = "content/cli"
