# Simple Blog Configuration
# =========================

site:
  title: "My Blog"
  author: "Jane Doe"
  baseurl: "https://myblog.com"
  description: "A simple blog built with Bengal"
  language: "en"
  
theme:
  name: "default"
  default_appearance: "system"
  
# Navigation menu
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Posts"
      url: "/posts/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 3

# Taxonomies
taxonomies:
  - tags
  - categories

