# Bengal SSG - Showcase Site Configuration
# This site demonstrates ALL Bengal features comprehensively

[site]
title = "Bengal SSG - Complete Showcase"
description = "A comprehensive demonstration of all Bengal SSG features, directives, and template functions"
baseurl = "https://bengal-ssg.dev"
language = "en"
author = "Bengal Team"

[build]
content_dir = "content"
output_dir = "public"
theme = "default"
draft = false
parallel = true
incremental = true
minify_html = true
max_workers = 10

# Enable all output formats
[build.output_formats]
html = true
json = true
llm_txt = true

[markdown]
parser = "mistune"
table_of_contents = true
gfm = true

[features]
syntax_highlighting = true
search = true
analytics = false

[taxonomies]
tags = "tags"
categories = "categories"
series = "series"

[menus]

[[menus.main]]
name = "Home"
url = "/"
weight = 1

[[menus.main]]
name = "Documentation"
url = "/docs/"
weight = 2

[[menus.main]]
name = "Examples"
url = "/examples/"
weight = 3

[[menus.main]]
name = "Blog"
url = "/blog/"
weight = 4

[[menus.main]]
name = "API"
url = "/api/"
weight = 5

[params]
# Custom site parameters
version = "1.0.0"
github_url = "https://github.com/yourusername/bengal"
show_reading_time = true
show_toc = true
show_breadcrumbs = true
enable_dark_mode = true

