# Bengal SSG - Showcase Site Configuration
# This site demonstrates ALL Bengal features comprehensively

[site]
title = "ᓚᘏᗢ Bengal SSG"
description = "A comprehensive demonstration of all Bengal SSG features, directives, and template functions"
baseurl = "https://bengal-ssg.dev"
language = "en"
author = "Bengal Team"

[build]
content_dir = "content"
output_dir = "public"
theme = "default"
draft = false
parallel = true
incremental = true
minify_html = true
auto_regenerate_autodoc = true  # Auto-regenerate docs when source changes

# Enable all output formats
[build.output_formats]
html = true
json = true
llm_txt = true

[markdown]
parser = "mistune"
table_of_contents = true
gfm = true

[features]
syntax_highlighting = true
search = true
analytics = false

[taxonomies]
tags = "tags"
categories = "categories"
series = "series"

# Main navigation menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Documentation"
url = "/docs/"
weight = 2

[[menu.main]]
name = "API"
url = "/api/"
weight = 3

[[menu.main]]
name = "CLI"
url = "/cli/"
weight = 4

[params]
# Custom site parameters
version = "1.0.0"
github_url = "https://github.com/yourusername/bengal"
show_reading_time = true
show_toc = true
show_breadcrumbs = true
enable_dark_mode = true

# Autodoc Configuration - Generate Bengal API documentation
[autodoc.python]
enabled = true
source_dirs = ["../../bengal"]  # Document the main Bengal package
output_dir = "content/api"  # Generated API docs go here
docstring_style = "auto"  # Auto-detect docstring format

# Exclude test and cache files
exclude = [
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/migrations/*",
    "*/.pytest_cache/*",
]

# Member visibility
include_private = false  # Skip _private methods
include_special = false  # Skip __special__ methods


[autodoc.cli]
enabled = true
app_module = "bengal.cli:main"
framework = "click"
output_dir = "content/cli"
