"""Rosettes themes package.

Semantic token system for syntax highlighting with modern CSS support.
Provides palettes, CSS generation, and accessibility validation.

Quick Start:
    >>> from rosettes.themes import MONOKAI, generate_css
    >>> css = generate_css(MONOKAI)
    >>> print(css[:50])
    /* Generated by Rosettes - theme: monokai, style:

Types:
    - SyntaxRole: Semantic roles for code elements
    - SyntaxPalette: Immutable theme definition
    - AdaptivePalette: Light/dark adaptive theme
    - TerminalPalette: ANSI color palette for terminal

Palettes:
    Dark: MONOKAI, DRACULA, ONE_DARK
    Adaptive: GITHUB, CATPPUCCIN, NORD
    Bengal: BENGAL_TIGER, BENGAL_SNOW_LYNX, BENGAL_CHARCOAL

Functions:
    - generate_css(): Generate CSS stylesheet
    - validate_palette(): Check WCAG contrast
    - get_palette(): Get palette by name
    - list_palettes(): List available palettes
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from rosettes.themes._css import (
    PYGMENTS_CLASS_MAP,
    SEMANTIC_CLASS_MAP,
    generate_css,
    generate_css_vars,
    get_css_class,
)
from rosettes.themes._mapping import ROLE_MAPPING, get_role
from rosettes.themes._palette import AdaptivePalette, SyntaxPalette
from rosettes.themes._roles import SyntaxRole
from rosettes.themes._terminal import TerminalPalette
from rosettes.themes._validation import (
    WCAG_AA_LARGE,
    WCAG_AA_NORMAL,
    WCAG_AAA_NORMAL,
    ContrastWarning,
    contrast_ratio,
    is_dark_palette,
    validate_palette,
)

# Built-in palettes
from rosettes.themes.palettes import (
    BENGAL_CHARCOAL,
    BENGAL_SNOW_LYNX,
    BENGAL_TIGER,
    CATPPUCCIN,
    DRACULA,
    GITHUB,
    MONOKAI,
    NORD,
    ONE_DARK,
    TERMINAL_MONOKAI,
)

if TYPE_CHECKING:
    from typing import Literal

    CssClassStyle = Literal["semantic", "pygments"]

__all__ = [
    # Core types
    "SyntaxRole",
    "SyntaxPalette",
    "AdaptivePalette",
    "TerminalPalette",
    # Mappings
    "ROLE_MAPPING",
    "PYGMENTS_CLASS_MAP",
    "SEMANTIC_CLASS_MAP",
    "get_role",
    "get_css_class",
    # CSS generation
    "generate_css",
    "generate_css_vars",
    # Validation
    "validate_palette",
    "contrast_ratio",
    "is_dark_palette",
    "ContrastWarning",
    "WCAG_AA_NORMAL",
    "WCAG_AA_LARGE",
    "WCAG_AAA_NORMAL",
    # Dark palettes
    "MONOKAI",
    "DRACULA",
    "ONE_DARK",
    # Adaptive palettes
    "GITHUB",
    "CATPPUCCIN",
    "NORD",
    # Bengal palettes
    "BENGAL_TIGER",
    "BENGAL_SNOW_LYNX",
    "BENGAL_CHARCOAL",
    # Terminal palettes
    "TERMINAL_MONOKAI",
    # Registry
    "register_palette",
    "get_palette",
    "list_palettes",
    # Type alias
    "Palette",
]


# Type alias for any palette type
Palette = SyntaxPalette | AdaptivePalette


# Palette registry (populated with built-ins)
_PALETTES: dict[str, Palette] = {}


def _init_registry() -> None:
    """Initialize the palette registry with built-in palettes."""
    global _PALETTES

    # Dark themes
    _PALETTES["monokai"] = MONOKAI
    _PALETTES["dracula"] = DRACULA
    _PALETTES["one-dark"] = ONE_DARK

    # Adaptive themes
    _PALETTES["github"] = GITHUB
    _PALETTES["github-light"] = GITHUB.light
    _PALETTES["github-dark"] = GITHUB.dark
    _PALETTES["catppuccin"] = CATPPUCCIN
    _PALETTES["catppuccin-latte"] = CATPPUCCIN.light
    _PALETTES["catppuccin-mocha"] = CATPPUCCIN.dark
    _PALETTES["nord"] = NORD
    _PALETTES["nord-light"] = NORD.light
    _PALETTES["nord-dark"] = NORD.dark

    # Bengal themes
    _PALETTES["bengal-tiger"] = BENGAL_TIGER
    _PALETTES["bengal-snow-lynx"] = BENGAL_SNOW_LYNX
    _PALETTES["bengal-charcoal"] = BENGAL_CHARCOAL


def register_palette(palette: Palette) -> None:
    """Register a custom palette.

    Args:
        palette: The palette to register.

    Example:
        >>> my_palette = SyntaxPalette(name="my-theme", ...)
        >>> register_palette(my_palette)
        >>> get_palette("my-theme")
        SyntaxPalette(name='my-theme', ...)
    """
    _PALETTES[palette.name] = palette


def get_palette(name: str) -> Palette:
    """Get a registered palette by name.

    Args:
        name: The palette name.

    Returns:
        The requested palette.

    Raises:
        KeyError: If the palette is not registered.

    Example:
        >>> palette = get_palette("monokai")
        >>> palette.name
        'monokai'
    """
    # Lazy init
    if not _PALETTES:
        _init_registry()

    if name not in _PALETTES:
        available = ", ".join(sorted(_PALETTES.keys()))
        raise KeyError(f"Unknown palette: {name!r}. Available: {available}")

    return _PALETTES[name]


def list_palettes() -> list[str]:
    """List all registered palette names.

    Returns:
        Sorted list of palette names.

    Example:
        >>> names = list_palettes()
        >>> "monokai" in names
        True
    """
    # Lazy init
    if not _PALETTES:
        _init_registry()

    return sorted(_PALETTES.keys())
