"""Rosettes themes package.

Semantic token system for syntax highlighting with modern CSS support.
Provides palettes, CSS generation, and accessibility validation.

All palettes are lazy-loaded on first access for fast import times.

Quick Start:
    >>> from rosettes.themes import MONOKAI, generate_css
    >>> css = generate_css(MONOKAI)
    >>> print(css[:50])
    /* Generated by Rosettes - theme: monokai, style:

Types:
    - SyntaxRole: Semantic roles for code elements
    - SyntaxPalette: Immutable theme definition
    - AdaptivePalette: Light/dark adaptive theme
    - TerminalPalette: ANSI color palette for terminal

Palettes:
    Dark: MONOKAI, DRACULA, ONE_DARK
    Adaptive: GITHUB, CATPPUCCIN, NORD
    Bengal: BENGAL_TIGER, BENGAL_SNOW_LYNX, BENGAL_CHARCOAL

Functions:
    - generate_css(): Generate CSS stylesheet
    - validate_palette(): Check WCAG contrast
    - get_palette(): Get palette by name
    - list_palettes(): List available palettes
"""

from __future__ import annotations

from typing import TYPE_CHECKING

# Core types - these are lightweight, OK to import eagerly
from rosettes.themes._palette import AdaptivePalette, SyntaxPalette
from rosettes.themes._roles import SyntaxRole
from rosettes.themes._terminal import TerminalPalette

# Validation utilities
from rosettes.themes._validation import (
    WCAG_AA_LARGE,
    WCAG_AA_NORMAL,
    WCAG_AAA_NORMAL,
    ContrastWarning,
    contrast_ratio,
    is_dark_palette,
    validate_palette,
)

if TYPE_CHECKING:
    from typing import Literal

    CssClassStyle = Literal["semantic", "pygments"]

__all__ = [
    # Core types
    "SyntaxRole",
    "SyntaxPalette",
    "AdaptivePalette",
    "TerminalPalette",
    # Mappings (lazy)
    "ROLE_MAPPING",
    "PYGMENTS_CLASS_MAP",
    "SEMANTIC_CLASS_MAP",
    "get_role",
    "get_css_class",
    # CSS generation (lazy)
    "generate_css",
    "generate_css_vars",
    # Validation
    "validate_palette",
    "contrast_ratio",
    "is_dark_palette",
    "ContrastWarning",
    "WCAG_AA_NORMAL",
    "WCAG_AA_LARGE",
    "WCAG_AAA_NORMAL",
    # Dark palettes (lazy)
    "MONOKAI",
    "DRACULA",
    "ONE_DARK",
    # Adaptive palettes (lazy)
    "GITHUB",
    "CATPPUCCIN",
    "NORD",
    # Bengal palettes (lazy)
    "BENGAL_TIGER",
    "BENGAL_SNOW_LYNX",
    "BENGAL_CHARCOAL",
    # Terminal palettes (lazy)
    "TERMINAL_MONOKAI",
    # Registry
    "register_palette",
    "get_palette",
    "list_palettes",
    # Type alias
    "Palette",
]


# Type alias for any palette type
Palette = SyntaxPalette | AdaptivePalette

# Palette names that are lazy-loaded
_PALETTE_NAMES = frozenset(
    {
        "MONOKAI",
        "DRACULA",
        "ONE_DARK",
        "GITHUB",
        "CATPPUCCIN",
        "NORD",
        "BENGAL_TIGER",
        "BENGAL_SNOW_LYNX",
        "BENGAL_CHARCOAL",
        "TERMINAL_MONOKAI",
    }
)

# Mapping names that are lazy-loaded
_MAPPING_NAMES = frozenset(
    {
        "ROLE_MAPPING",
        "PYGMENTS_CLASS_MAP",
        "SEMANTIC_CLASS_MAP",
        "get_role",
        "get_css_class",
        "generate_css",
        "generate_css_vars",
    }
)

# Cache for lazy-loaded items
_lazy_cache: dict[str, object] = {}


def __getattr__(name: str) -> object:
    """Lazy-load palettes and mappings on first access."""
    if name in _lazy_cache:
        return _lazy_cache[name]

    # Lazy-load palettes from palettes subpackage
    if name in _PALETTE_NAMES:
        from rosettes.themes import palettes

        result = getattr(palettes, name)
        _lazy_cache[name] = result
        return result

    # Lazy-load mappings from _mapping module
    if name in {"ROLE_MAPPING", "get_role"}:
        from rosettes.themes._mapping import ROLE_MAPPING, get_role

        _lazy_cache["ROLE_MAPPING"] = ROLE_MAPPING
        _lazy_cache["get_role"] = get_role
        return _lazy_cache[name]

    # Lazy-load CSS utilities from _css module
    if name in {
        "PYGMENTS_CLASS_MAP",
        "SEMANTIC_CLASS_MAP",
        "get_css_class",
        "generate_css",
        "generate_css_vars",
    }:
        from rosettes.themes._css import (
            PYGMENTS_CLASS_MAP,
            SEMANTIC_CLASS_MAP,
            generate_css,
            generate_css_vars,
            get_css_class,
        )

        _lazy_cache["PYGMENTS_CLASS_MAP"] = PYGMENTS_CLASS_MAP
        _lazy_cache["SEMANTIC_CLASS_MAP"] = SEMANTIC_CLASS_MAP
        _lazy_cache["get_css_class"] = get_css_class
        _lazy_cache["generate_css"] = generate_css
        _lazy_cache["generate_css_vars"] = generate_css_vars
        return _lazy_cache[name]

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    """List available attributes for tab completion."""
    return list(__all__)


# Palette registry (populated lazily)
_PALETTES: dict[str, Palette] = {}


def _init_registry() -> None:
    """Initialize the palette registry with built-in palettes."""
    global _PALETTES

    # Import palettes lazily
    from rosettes.themes import palettes

    # Dark themes
    _PALETTES["monokai"] = palettes.MONOKAI
    _PALETTES["dracula"] = palettes.DRACULA
    _PALETTES["one-dark"] = palettes.ONE_DARK

    # Adaptive themes
    _PALETTES["github"] = palettes.GITHUB
    _PALETTES["github-light"] = palettes.GITHUB.light
    _PALETTES["github-dark"] = palettes.GITHUB.dark
    _PALETTES["catppuccin"] = palettes.CATPPUCCIN
    _PALETTES["catppuccin-latte"] = palettes.CATPPUCCIN.light
    _PALETTES["catppuccin-mocha"] = palettes.CATPPUCCIN.dark
    _PALETTES["nord"] = palettes.NORD
    _PALETTES["nord-light"] = palettes.NORD.light
    _PALETTES["nord-dark"] = palettes.NORD.dark

    # Bengal themes
    _PALETTES["bengal-tiger"] = palettes.BENGAL_TIGER
    _PALETTES["bengal-snow-lynx"] = palettes.BENGAL_SNOW_LYNX
    _PALETTES["bengal-charcoal"] = palettes.BENGAL_CHARCOAL


def register_palette(palette: Palette) -> None:
    """Register a custom palette.

    Args:
        palette: The palette to register.

    Example:
        >>> my_palette = SyntaxPalette(name="my-theme", ...)
        >>> register_palette(my_palette)
        >>> get_palette("my-theme")
        SyntaxPalette(name='my-theme', ...)
    """
    _PALETTES[palette.name] = palette


def get_palette(name: str) -> Palette:
    """Get a registered palette by name.

    Args:
        name: The palette name.

    Returns:
        The requested palette.

    Raises:
        KeyError: If the palette is not registered.

    Example:
        >>> palette = get_palette("monokai")
        >>> palette.name
        'monokai'
    """
    # Lazy init
    if not _PALETTES:
        _init_registry()

    if name not in _PALETTES:
        available = ", ".join(sorted(_PALETTES.keys()))
        raise KeyError(f"Unknown palette: {name!r}. Available: {available}")

    return _PALETTES[name]


def list_palettes() -> list[str]:
    """List all registered palette names.

    Returns:
        Sorted list of palette names.

    Example:
        >>> names = list_palettes()
        >>> "monokai" in names
        True
    """
    # Lazy init
    if not _PALETTES:
        _init_registry()

    return sorted(_PALETTES.keys())
