"""CSS generation for Rosettes themes.

Generates modern CSS with semantic classes, CSS custom properties,
and optional Pygments-compatible output.

Thread-safe: All functions are pure (no side effects).

Modern CSS Features:
    - @layer for cascade control
    - color-mix() for dynamic variants
    - light-dark() for native adaptation
    - Container queries for responsive code blocks
    - CSS nesting (with flat fallback)
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from rosettes.themes._roles import SyntaxRole

if TYPE_CHECKING:
    from typing import Literal

    from rosettes.themes._palette import SyntaxPalette

    CssClassStyle = Literal["semantic", "pygments"]

__all__ = ["generate_css", "generate_css_vars", "get_css_class", "CssClassStyle"]


# Role to CSS class mapping for semantic mode
SEMANTIC_CLASS_MAP: dict[SyntaxRole, str] = {
    SyntaxRole.CONTROL_FLOW: "syntax-control",
    SyntaxRole.DECLARATION: "syntax-declaration",
    SyntaxRole.IMPORT: "syntax-import",
    SyntaxRole.STRING: "syntax-string",
    SyntaxRole.DOCSTRING: "syntax-docstring",
    SyntaxRole.NUMBER: "syntax-number",
    SyntaxRole.BOOLEAN: "syntax-boolean",
    SyntaxRole.TYPE: "syntax-type",
    SyntaxRole.FUNCTION: "syntax-function",
    SyntaxRole.VARIABLE: "syntax-variable",
    SyntaxRole.CONSTANT: "syntax-constant",
    SyntaxRole.COMMENT: "syntax-comment",
    SyntaxRole.ERROR: "syntax-error",
    SyntaxRole.WARNING: "syntax-warning",
    SyntaxRole.ADDED: "syntax-added",
    SyntaxRole.REMOVED: "syntax-removed",
    SyntaxRole.TEXT: "syntax-text",
    SyntaxRole.MUTED: "syntax-muted",
    SyntaxRole.PUNCTUATION: "syntax-punctuation",
    SyntaxRole.OPERATOR: "syntax-operator",
    SyntaxRole.ATTRIBUTE: "syntax-attribute",
    SyntaxRole.NAMESPACE: "syntax-namespace",
    SyntaxRole.TAG: "syntax-tag",
    SyntaxRole.REGEX: "syntax-regex",
    SyntaxRole.ESCAPE: "syntax-escape",
}


# Role to Pygments class mapping for compatibility mode
PYGMENTS_CLASS_MAP: dict[SyntaxRole, str] = {
    SyntaxRole.CONTROL_FLOW: "k",
    SyntaxRole.DECLARATION: "kd",
    SyntaxRole.IMPORT: "kn",
    SyntaxRole.STRING: "s",
    SyntaxRole.DOCSTRING: "sd",
    SyntaxRole.NUMBER: "m",
    SyntaxRole.BOOLEAN: "kc",
    SyntaxRole.TYPE: "nc",
    SyntaxRole.FUNCTION: "nf",
    SyntaxRole.VARIABLE: "nv",
    SyntaxRole.CONSTANT: "no",
    SyntaxRole.COMMENT: "c",
    SyntaxRole.ERROR: "err",
    SyntaxRole.WARNING: "w",
    SyntaxRole.ADDED: "gi",
    SyntaxRole.REMOVED: "gd",
    SyntaxRole.TEXT: "",
    SyntaxRole.MUTED: "x",
    SyntaxRole.PUNCTUATION: "p",
    SyntaxRole.OPERATOR: "o",
    SyntaxRole.ATTRIBUTE: "nd",
    SyntaxRole.NAMESPACE: "nn",
    SyntaxRole.TAG: "nt",
    SyntaxRole.REGEX: "sr",
    SyntaxRole.ESCAPE: "se",
}


def get_css_class(role: SyntaxRole, style: CssClassStyle = "semantic") -> str:
    """Get CSS class name for a role.

    Args:
        role: The semantic role.
        style: "semantic" for .syntax-* or "pygments" for .k, .nf, etc.

    Returns:
        The CSS class name.
    """
    if style == "semantic":
        return SEMANTIC_CLASS_MAP.get(role, f"syntax-{role.value}")
    return PYGMENTS_CLASS_MAP.get(role, "")


def generate_css_vars(
    palette: SyntaxPalette | None = None,
    indent: int = 0,
) -> str:
    """Generate CSS custom property declarations.

    Args:
        palette: The palette to generate vars for. If None, uses CSS var references.
        indent: Number of spaces to indent.

    Returns:
        CSS custom property declarations.
    """
    if palette is None:
        # Return reference-only CSS (for when vars are defined elsewhere)
        return ""

    return palette.to_css_vars(indent)


def generate_css(
    palette: SyntaxPalette | None = None,
    *,
    css_class_style: CssClassStyle = "semantic",
    use_layer: bool = True,
    use_nesting: bool = False,
    include_vars: bool = True,
    include_container_queries: bool = True,
) -> str:
    """Generate complete CSS stylesheet for syntax highlighting.

    Args:
        palette: The palette to use. If None, generates CSS using var references.
        css_class_style: "semantic" for .syntax-* or "pygments" for .k, .nf, etc.
        use_layer: If True, wrap styles in @layer rosettes.
        use_nesting: If True, use CSS nesting syntax (88%+ browser support).
        include_vars: If True, include CSS custom property declarations.
        include_container_queries: If True, include container query styles.

    Returns:
        Complete CSS stylesheet as a string.
    """
    lines: list[str] = []

    # Header
    if palette:
        lines.append(
            f"/* Generated by Rosettes - theme: {palette.name}, style: {css_class_style} */"
        )
    else:
        lines.append(f"/* Generated by Rosettes - style: {css_class_style} */")
    lines.append("")

    # CSS Variables
    if include_vars and palette:
        lines.append(":root {")
        lines.append("  /* Rosettes Syntax Palette */")
        lines.append(palette.to_css_vars(indent=2))
        lines.append("}")
        lines.append("")

    # Container class
    container = "rosettes" if css_class_style == "semantic" else "highlight"

    # Start layer if enabled
    if use_layer:
        lines.append("@layer rosettes {")

    # Generate styles
    if use_nesting:
        lines.extend(_generate_nested_css(container, css_class_style, use_layer))
    else:
        lines.extend(_generate_flat_css(container, css_class_style, use_layer))

    # Container queries
    if include_container_queries:
        lines.append("")
        lines.extend(_generate_container_queries(container, use_layer))

    # Close layer
    if use_layer:
        lines.append("}")

    return "\n".join(lines)


def _generate_flat_css(
    container: str,
    style: CssClassStyle,
    indent_layer: bool,
) -> list[str]:
    """Generate flat (non-nested) CSS rules."""
    lines: list[str] = []
    prefix = "  " if indent_layer else ""

    # Base container
    lines.append(f"{prefix}.{container} {{")
    lines.append(f"{prefix}  background: var(--syntax-bg);")
    lines.append(f"{prefix}  color: var(--syntax-text);")
    lines.append(
        f"{prefix}  font-family: var(--font-mono, ui-monospace, 'Cascadia Code', 'Source Code Pro', Menlo, Consolas, 'DejaVu Sans Mono', monospace);"
    )
    lines.append(f"{prefix}  font-size: var(--text-code, 0.875em);")
    lines.append(f"{prefix}  line-height: var(--line-height-relaxed, 1.7);")
    lines.append(f"{prefix}  border-radius: var(--radius-lg, 0.5rem);")
    lines.append(f"{prefix}  padding: var(--spacing-4, 1rem);")
    lines.append(f"{prefix}  overflow-x: auto;")
    lines.append(f"{prefix}  tab-size: 4;")
    lines.append(f"{prefix}}}")
    lines.append("")

    # Line highlight
    lines.append(f"{prefix}.{container} .line-highlight,")
    lines.append(f"{prefix}.{container} .hll {{")
    lines.append(f"{prefix}  background: var(--syntax-bg-highlight);")
    lines.append(f"{prefix}  display: block;")
    lines.append(f"{prefix}  margin: 0 calc(var(--spacing-4, 1rem) * -1);")
    lines.append(f"{prefix}  padding: 0 var(--spacing-4, 1rem);")
    lines.append(f"{prefix}}}")
    lines.append("")

    # Token classes
    if style == "semantic":
        lines.extend(_generate_semantic_token_classes(container, prefix))
    else:
        lines.extend(_generate_pygments_token_classes(container, prefix))

    return lines


def _generate_semantic_token_classes(container: str, prefix: str) -> list[str]:
    """Generate semantic token class rules."""
    lines: list[str] = []

    # Control & Structure
    lines.append(f"{prefix}/* Control & Structure */")
    lines.append(f"{prefix}.{container} .syntax-control {{")
    lines.append(f"{prefix}  color: var(--syntax-control);")
    lines.append(f"{prefix}  font-weight: 600;")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-declaration {{")
    lines.append(f"{prefix}  color: var(--syntax-declaration);")
    lines.append(f"{prefix}  font-weight: 600;")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-import {{")
    lines.append(f"{prefix}  color: var(--syntax-import);")
    lines.append(f"{prefix}}}")
    lines.append("")

    # Data & Literals
    lines.append(f"{prefix}/* Data & Literals */")
    lines.append(f"{prefix}.{container} .syntax-string {{")
    lines.append(f"{prefix}  color: var(--syntax-string);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-docstring {{")
    lines.append(f"{prefix}  color: var(--syntax-docstring);")
    lines.append(f"{prefix}  font-style: italic;")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-number {{")
    lines.append(f"{prefix}  color: var(--syntax-number);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-boolean {{")
    lines.append(f"{prefix}  color: var(--syntax-boolean);")
    lines.append(f"{prefix}}}")
    lines.append("")

    # Identifiers
    lines.append(f"{prefix}/* Identifiers */")
    lines.append(f"{prefix}.{container} .syntax-type {{")
    lines.append(f"{prefix}  color: var(--syntax-type);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-function {{")
    lines.append(f"{prefix}  color: var(--syntax-function);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-variable {{")
    lines.append(f"{prefix}  color: var(--syntax-variable);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-constant {{")
    lines.append(f"{prefix}  color: var(--syntax-constant);")
    lines.append(f"{prefix}}}")
    lines.append("")

    # Documentation
    lines.append(f"{prefix}/* Documentation */")
    lines.append(f"{prefix}.{container} .syntax-comment {{")
    lines.append(f"{prefix}  color: var(--syntax-comment);")
    lines.append(f"{prefix}  font-style: italic;")
    lines.append(f"{prefix}}}")
    lines.append("")

    # Feedback
    lines.append(f"{prefix}/* Feedback */")
    lines.append(f"{prefix}.{container} .syntax-error {{")
    lines.append(f"{prefix}  color: var(--syntax-error);")
    lines.append(f"{prefix}  text-decoration: wavy underline var(--syntax-error);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-warning {{")
    lines.append(f"{prefix}  color: var(--syntax-warning);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-added {{")
    lines.append(f"{prefix}  color: var(--syntax-added);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-removed {{")
    lines.append(f"{prefix}  color: var(--syntax-removed);")
    lines.append(f"{prefix}}}")
    lines.append("")

    # Additional roles
    lines.append(f"{prefix}/* Additional */")
    lines.append(f"{prefix}.{container} .syntax-punctuation {{")
    lines.append(f"{prefix}  color: var(--syntax-punctuation);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-operator {{")
    lines.append(f"{prefix}  color: var(--syntax-operator);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-attribute {{")
    lines.append(f"{prefix}  color: var(--syntax-attribute);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-namespace {{")
    lines.append(f"{prefix}  color: var(--syntax-namespace);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-tag {{")
    lines.append(f"{prefix}  color: var(--syntax-tag);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-regex {{")
    lines.append(f"{prefix}  color: var(--syntax-regex);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-escape {{")
    lines.append(f"{prefix}  color: var(--syntax-escape);")
    lines.append(f"{prefix}}}")
    lines.append(f"{prefix}.{container} .syntax-muted {{")
    lines.append(f"{prefix}  color: var(--syntax-muted);")
    lines.append(f"{prefix}}}")

    return lines


def _generate_pygments_token_classes(container: str, prefix: str) -> list[str]:
    """Generate Pygments-compatible token class rules."""
    lines: list[str] = []

    # Keywords
    lines.append(f"{prefix}/* Keywords */")
    lines.append(f"{prefix}.{container} .k {{ color: var(--syntax-control); font-weight: 600; }}")
    lines.append(f"{prefix}.{container} .kc {{ color: var(--syntax-boolean); }}")
    lines.append(
        f"{prefix}.{container} .kd {{ color: var(--syntax-declaration); font-weight: 600; }}"
    )
    lines.append(f"{prefix}.{container} .kn {{ color: var(--syntax-import); }}")
    lines.append(f"{prefix}.{container} .kp {{ color: var(--syntax-control); }}")
    lines.append(f"{prefix}.{container} .kr {{ color: var(--syntax-control); }}")
    lines.append(f"{prefix}.{container} .kt {{ color: var(--syntax-type); }}")
    lines.append("")

    # Names
    lines.append(f"{prefix}/* Names */")
    lines.append(f"{prefix}.{container} .n {{ color: var(--syntax-variable); }}")
    lines.append(f"{prefix}.{container} .na {{ color: var(--syntax-attribute); }}")
    lines.append(f"{prefix}.{container} .nb {{ color: var(--syntax-function); }}")
    lines.append(f"{prefix}.{container} .bp {{ color: var(--syntax-constant); }}")
    lines.append(f"{prefix}.{container} .nc {{ color: var(--syntax-type); }}")
    lines.append(f"{prefix}.{container} .no {{ color: var(--syntax-constant); }}")
    lines.append(f"{prefix}.{container} .nd {{ color: var(--syntax-attribute); }}")
    lines.append(f"{prefix}.{container} .ni {{ color: var(--syntax-constant); }}")
    lines.append(f"{prefix}.{container} .ne {{ color: var(--syntax-type); }}")
    lines.append(f"{prefix}.{container} .nf {{ color: var(--syntax-function); }}")
    lines.append(f"{prefix}.{container} .fm {{ color: var(--syntax-function); }}")
    lines.append(f"{prefix}.{container} .nl {{ color: var(--syntax-variable); }}")
    lines.append(f"{prefix}.{container} .nn {{ color: var(--syntax-namespace); }}")
    lines.append(f"{prefix}.{container} .nx {{ color: var(--syntax-variable); }}")
    lines.append(f"{prefix}.{container} .py {{ color: var(--syntax-attribute); }}")
    lines.append(f"{prefix}.{container} .nt {{ color: var(--syntax-tag); }}")
    lines.append(f"{prefix}.{container} .nv {{ color: var(--syntax-variable); }}")
    lines.append(f"{prefix}.{container} .vc {{ color: var(--syntax-variable); }}")
    lines.append(f"{prefix}.{container} .vg {{ color: var(--syntax-variable); }}")
    lines.append(f"{prefix}.{container} .vi {{ color: var(--syntax-variable); }}")
    lines.append(f"{prefix}.{container} .vm {{ color: var(--syntax-constant); }}")
    lines.append("")

    # Strings
    lines.append(f"{prefix}/* Strings */")
    lines.append(f"{prefix}.{container} .s {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}.{container} .sa {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}.{container} .sb {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}.{container} .sc {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}.{container} .dl {{ color: var(--syntax-string); }}")
    lines.append(
        f"{prefix}.{container} .sd {{ color: var(--syntax-docstring); font-style: italic; }}"
    )
    lines.append(f"{prefix}.{container} .s2 {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}.{container} .se {{ color: var(--syntax-escape); }}")
    lines.append(f"{prefix}.{container} .sh {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}.{container} .si {{ color: var(--syntax-escape); }}")
    lines.append(f"{prefix}.{container} .sx {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}.{container} .sr {{ color: var(--syntax-regex); }}")
    lines.append(f"{prefix}.{container} .s1 {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}.{container} .ss {{ color: var(--syntax-constant); }}")
    lines.append("")

    # Numbers
    lines.append(f"{prefix}/* Numbers */")
    lines.append(f"{prefix}.{container} .m {{ color: var(--syntax-number); }}")
    lines.append(f"{prefix}.{container} .mb {{ color: var(--syntax-number); }}")
    lines.append(f"{prefix}.{container} .mf {{ color: var(--syntax-number); }}")
    lines.append(f"{prefix}.{container} .mh {{ color: var(--syntax-number); }}")
    lines.append(f"{prefix}.{container} .mi {{ color: var(--syntax-number); }}")
    lines.append(f"{prefix}.{container} .il {{ color: var(--syntax-number); }}")
    lines.append(f"{prefix}.{container} .mo {{ color: var(--syntax-number); }}")
    lines.append("")

    # Operators & Punctuation
    lines.append(f"{prefix}/* Operators & Punctuation */")
    lines.append(f"{prefix}.{container} .o {{ color: var(--syntax-operator); }}")
    lines.append(f"{prefix}.{container} .ow {{ color: var(--syntax-control); }}")
    lines.append(f"{prefix}.{container} .p {{ color: var(--syntax-punctuation); }}")
    lines.append(f"{prefix}.{container} .pm {{ color: var(--syntax-punctuation); }}")
    lines.append("")

    # Comments
    lines.append(f"{prefix}/* Comments */")
    lines.append(f"{prefix}.{container} .c {{ color: var(--syntax-comment); font-style: italic; }}")
    lines.append(
        f"{prefix}.{container} .ch {{ color: var(--syntax-comment); font-style: italic; }}"
    )
    lines.append(
        f"{prefix}.{container} .cm {{ color: var(--syntax-comment); font-style: italic; }}"
    )
    lines.append(f"{prefix}.{container} .cp {{ color: var(--syntax-attribute); }}")
    lines.append(f"{prefix}.{container} .cpf {{ color: var(--syntax-string); }}")
    lines.append(
        f"{prefix}.{container} .c1 {{ color: var(--syntax-comment); font-style: italic; }}"
    )
    lines.append(
        f"{prefix}.{container} .cs {{ color: var(--syntax-docstring); font-style: italic; }}"
    )
    lines.append("")

    # Generic
    lines.append(f"{prefix}/* Generic */")
    lines.append(f"{prefix}.{container} .gd {{ color: var(--syntax-removed); }}")
    lines.append(f"{prefix}.{container} .ge {{ font-style: italic; }}")
    lines.append(f"{prefix}.{container} .gr {{ color: var(--syntax-error); }}")
    lines.append(
        f"{prefix}.{container} .gh {{ color: var(--syntax-declaration); font-weight: 600; }}"
    )
    lines.append(f"{prefix}.{container} .gi {{ color: var(--syntax-added); }}")
    lines.append(f"{prefix}.{container} .go {{ color: var(--syntax-muted); }}")
    lines.append(f"{prefix}.{container} .gp {{ color: var(--syntax-muted); }}")
    lines.append(f"{prefix}.{container} .gs {{ font-weight: 700; }}")
    lines.append(f"{prefix}.{container} .gu {{ color: var(--syntax-declaration); }}")
    lines.append(f"{prefix}.{container} .gt {{ color: var(--syntax-error); }}")
    lines.append("")

    # Special
    lines.append(f"{prefix}/* Special */")
    lines.append(f"{prefix}.{container} .w {{ color: var(--syntax-muted); }}")
    lines.append(
        f"{prefix}.{container} .err {{ color: var(--syntax-error); text-decoration: wavy underline var(--syntax-error); }}"
    )
    lines.append(f"{prefix}.{container} .x {{ color: var(--syntax-muted); }}")

    return lines


def _generate_nested_css(
    container: str,
    style: CssClassStyle,
    indent_layer: bool,
) -> list[str]:
    """Generate CSS using native nesting syntax."""
    lines: list[str] = []
    prefix = "  " if indent_layer else ""

    # Base container with nested rules
    lines.append(f"{prefix}.{container} {{")
    lines.append(f"{prefix}  background: var(--syntax-bg);")
    lines.append(f"{prefix}  color: var(--syntax-text);")
    lines.append(
        f"{prefix}  font-family: var(--font-mono, ui-monospace, 'Cascadia Code', 'Source Code Pro', Menlo, Consolas, 'DejaVu Sans Mono', monospace);"
    )
    lines.append(f"{prefix}  font-size: var(--text-code, 0.875em);")
    lines.append(f"{prefix}  line-height: var(--line-height-relaxed, 1.7);")
    lines.append(f"{prefix}  border-radius: var(--radius-lg, 0.5rem);")
    lines.append(f"{prefix}  padding: var(--spacing-4, 1rem);")
    lines.append(f"{prefix}  overflow-x: auto;")
    lines.append(f"{prefix}  tab-size: 4;")
    lines.append("")

    # Line highlight (nested)
    lines.append(f"{prefix}  & .line-highlight,")
    lines.append(f"{prefix}  & .hll {{")
    lines.append(f"{prefix}    background: var(--syntax-bg-highlight);")
    lines.append(f"{prefix}    display: block;")
    lines.append(f"{prefix}    margin: 0 calc(var(--spacing-4, 1rem) * -1);")
    lines.append(f"{prefix}    padding: 0 var(--spacing-4, 1rem);")
    lines.append(f"{prefix}  }}")
    lines.append("")

    # Token classes (nested)
    if style == "semantic":
        lines.extend(_generate_nested_semantic_classes(prefix))
    else:
        lines.extend(_generate_nested_pygments_classes(prefix))

    lines.append(f"{prefix}}}")

    return lines


def _generate_nested_semantic_classes(prefix: str) -> list[str]:
    """Generate nested semantic token classes."""
    lines: list[str] = []

    lines.append(f"{prefix}  /* Control & Structure */")
    lines.append(
        f"{prefix}  & .syntax-control {{ color: var(--syntax-control); font-weight: 600; }}"
    )
    lines.append(
        f"{prefix}  & .syntax-declaration {{ color: var(--syntax-declaration); font-weight: 600; }}"
    )
    lines.append(f"{prefix}  & .syntax-import {{ color: var(--syntax-import); }}")
    lines.append("")
    lines.append(f"{prefix}  /* Data & Literals */")
    lines.append(f"{prefix}  & .syntax-string {{ color: var(--syntax-string); }}")
    lines.append(
        f"{prefix}  & .syntax-docstring {{ color: var(--syntax-docstring); font-style: italic; }}"
    )
    lines.append(f"{prefix}  & .syntax-number {{ color: var(--syntax-number); }}")
    lines.append(f"{prefix}  & .syntax-boolean {{ color: var(--syntax-boolean); }}")
    lines.append("")
    lines.append(f"{prefix}  /* Identifiers */")
    lines.append(f"{prefix}  & .syntax-type {{ color: var(--syntax-type); }}")
    lines.append(f"{prefix}  & .syntax-function {{ color: var(--syntax-function); }}")
    lines.append(f"{prefix}  & .syntax-variable {{ color: var(--syntax-variable); }}")
    lines.append(f"{prefix}  & .syntax-constant {{ color: var(--syntax-constant); }}")
    lines.append("")
    lines.append(f"{prefix}  /* Documentation */")
    lines.append(
        f"{prefix}  & .syntax-comment {{ color: var(--syntax-comment); font-style: italic; }}"
    )
    lines.append("")
    lines.append(f"{prefix}  /* Feedback */")
    lines.append(
        f"{prefix}  & .syntax-error {{ color: var(--syntax-error); text-decoration: wavy underline var(--syntax-error); }}"
    )
    lines.append(f"{prefix}  & .syntax-warning {{ color: var(--syntax-warning); }}")
    lines.append(f"{prefix}  & .syntax-added {{ color: var(--syntax-added); }}")
    lines.append(f"{prefix}  & .syntax-removed {{ color: var(--syntax-removed); }}")
    lines.append("")
    lines.append(f"{prefix}  /* Additional */")
    lines.append(f"{prefix}  & .syntax-punctuation {{ color: var(--syntax-punctuation); }}")
    lines.append(f"{prefix}  & .syntax-operator {{ color: var(--syntax-operator); }}")
    lines.append(f"{prefix}  & .syntax-attribute {{ color: var(--syntax-attribute); }}")
    lines.append(f"{prefix}  & .syntax-namespace {{ color: var(--syntax-namespace); }}")
    lines.append(f"{prefix}  & .syntax-tag {{ color: var(--syntax-tag); }}")
    lines.append(f"{prefix}  & .syntax-regex {{ color: var(--syntax-regex); }}")
    lines.append(f"{prefix}  & .syntax-escape {{ color: var(--syntax-escape); }}")
    lines.append(f"{prefix}  & .syntax-muted {{ color: var(--syntax-muted); }}")

    return lines


def _generate_nested_pygments_classes(prefix: str) -> list[str]:
    """Generate nested Pygments-compatible token classes."""
    lines: list[str] = []

    lines.append(f"{prefix}  /* Keywords */")
    lines.append(f"{prefix}  & .k {{ color: var(--syntax-control); font-weight: 600; }}")
    lines.append(f"{prefix}  & .kc {{ color: var(--syntax-boolean); }}")
    lines.append(f"{prefix}  & .kd {{ color: var(--syntax-declaration); font-weight: 600; }}")
    lines.append(f"{prefix}  & .kn {{ color: var(--syntax-import); }}")
    lines.append(f"{prefix}  & .kp {{ color: var(--syntax-control); }}")
    lines.append(f"{prefix}  & .kr {{ color: var(--syntax-control); }}")
    lines.append(f"{prefix}  & .kt {{ color: var(--syntax-type); }}")
    lines.append("")
    lines.append(f"{prefix}  /* Names */")
    lines.append(f"{prefix}  & .nc {{ color: var(--syntax-type); }}")
    lines.append(f"{prefix}  & .nf {{ color: var(--syntax-function); }}")
    lines.append(f"{prefix}  & .nd {{ color: var(--syntax-attribute); }}")
    lines.append(f"{prefix}  & .no {{ color: var(--syntax-constant); }}")
    lines.append(f"{prefix}  & .nv {{ color: var(--syntax-variable); }}")
    lines.append("")
    lines.append(f"{prefix}  /* Strings & Numbers */")
    lines.append(f"{prefix}  & .s {{ color: var(--syntax-string); }}")
    lines.append(f"{prefix}  & .sd {{ color: var(--syntax-docstring); font-style: italic; }}")
    lines.append(f"{prefix}  & .m {{ color: var(--syntax-number); }}")
    lines.append("")
    lines.append(f"{prefix}  /* Comments */")
    lines.append(f"{prefix}  & .c {{ color: var(--syntax-comment); font-style: italic; }}")
    lines.append("")
    lines.append(f"{prefix}  /* Generic */")
    lines.append(f"{prefix}  & .gi {{ color: var(--syntax-added); }}")
    lines.append(f"{prefix}  & .gd {{ color: var(--syntax-removed); }}")
    lines.append(
        f"{prefix}  & .err {{ color: var(--syntax-error); text-decoration: wavy underline; }}"
    )

    return lines


def _generate_container_queries(container: str, indent_layer: bool) -> list[str]:
    """Generate container query styles for responsive code blocks."""
    lines: list[str] = []
    prefix = "  " if indent_layer else ""

    lines.append(f"{prefix}/* Container queries for responsive code blocks */")
    lines.append(f"{prefix}.{container} {{")
    lines.append(f"{prefix}  container-type: inline-size;")
    lines.append(f"{prefix}  container-name: code-block;")
    lines.append(f"{prefix}}}")
    lines.append("")

    lines.append(f"{prefix}@container code-block (max-width: 400px) {{")
    lines.append(f"{prefix}  .{container} code {{")
    lines.append(f"{prefix}    font-size: var(--text-xs, 0.75em);")
    lines.append(f"{prefix}  }}")
    lines.append(f"{prefix}}}")
    lines.append("")

    lines.append(f"{prefix}@container code-block (max-width: 300px) {{")
    lines.append(f"{prefix}  .{container} .line-numbers {{")
    lines.append(f"{prefix}    display: none;")
    lines.append(f"{prefix}  }}")
    lines.append(f"{prefix}}}")

    return lines
