"""Pure Kida filters eligible for compile-time folding.

Filters whose output depends only on their inputs (no site/page/I/O/time).
Kida's partial evaluator can fold these at compile time when all arguments
are constants from static_context.
"""

_PURE_FILTERS: set[str] = {
    # strings.py
    "truncatewords",
    "truncatewords_html",
    "slugify",
    "markdownify",
    "strip_html",
    "plainify",
    "truncate_chars",
    "replace_regex",
    "pluralize",
    "reading_time",
    "word_count",
    "wordcount",
    "excerpt",
    "excerpt_for_card",
    "card_excerpt",
    "card_excerpt_html",
    "strip_whitespace",
    "get",
    "first_sentence",
    "filesize",
    "split",
    "base64_encode",
    "base64_decode",
    # advanced_strings.py
    "camelize",
    "underscore",
    "titleize",
    "wrap",
    "indent",
    "softwrap_ident",
    "last_segment",
    "regex_search",
    "regex_findall",
    "trim_prefix",
    "trim_suffix",
    "has_prefix",
    "has_suffix",
    "contains",
    "to_sentence",
    # math_functions.py
    "percentage",
    "times",
    "divided_by",
    "ceil",
    "floor",
    "round",
    "coerce_int",
    # collections.py
    "where",
    "where_not",
    "group_by",
    "sort_by",
    "limit",
    "offset",
    "uniq",
    "flatten",
    "first",
    "last",
    "reverse",
    "union",
    "intersect",
    "complement",
    "group_by_year",
    "group_by_month",
    "archive_years",
    # advanced_collections.py
    "chunk",
    # dates.py (deterministic subset — excludes time_ago/days_ago/months_ago)
    "date_iso",
    "date_rfc822",
    "month_name",
    "humanize_days",
    "date_add",
    "date_diff",
    # data.py
    "jsonify",
    "merge",
    "has_key",
    "get_nested",
    "keys",
    "values",
    "items",
    # content.py
    "safe_html",
    "html_escape",
    "html_unescape",
    "nl2br",
    "smartquotes",
    "emojify",
    "extract_content",
    "demote_headings",
    "prefix_heading_ids",
    "urlize",
    "highlight",
    # seo.py
    "meta_description",
    "meta_keywords",
    # pagination_helpers.py
    "paginate",
    # images.py
    "image_srcset",
    "image_alt",
    # urls.py (deterministic subset — excludes absolute_url/href)
    "url_encode",
    "url_decode",
    "url_parse",
    "url_param",
    "url_query",
    # debug.py
    "debug",
    "typeof",
    "inspect",
    # autodoc.py
    "get_params",
    "param_count",
    "return_type",
    "get_return_info",
    "get_element_stats",
    "children_by_type",
    "public_only",
    "private_only",
    "is_autodoc_page",
    "members",
    "commands",
    "options",
    "member_view",
    "option_view",
    "command_view",
    # openapi.py
    "highlight_path_params",
    "method_color_class",
    "status_code_class",
    "endpoints",
    "schemas",
    # changelog.py
    "releases",
    "release_view",
    # taxonomies.py (deterministic subset)
    "has_tag",
    "tag_accent_index",
    # blog.py (deterministic subset)
    "posts",
    "post_view",
    "featured_posts",
}
