"""Tests for Rosettes theming system."""

import pytest

from rosettes import highlight
from rosettes.themes import (
    BENGAL_TIGER,
    CATPPUCCIN,
    DRACULA,
    GITHUB,
    MONOKAI,
    NORD,
    ONE_DARK,
    TERMINAL_MONOKAI,
    AdaptivePalette,
    SyntaxPalette,
    SyntaxRole,
    TerminalPalette,
    contrast_ratio,
    generate_css,
    get_palette,
    is_dark_palette,
    list_palettes,
    register_palette,
    validate_palette,
)


class TestSyntaxRole:
    """Tests for SyntaxRole enum."""

    def test_role_values(self) -> None:
        """Roles have expected string values."""
        assert SyntaxRole.CONTROL_FLOW.value == "control"
        assert SyntaxRole.STRING.value == "string"
        assert SyntaxRole.FUNCTION.value == "function"

    def test_all_roles_defined(self) -> None:
        """All expected roles are defined."""
        expected_roles = {
            "control",
            "declaration",
            "import",
            "string",
            "number",
            "boolean",
            "type",
            "function",
            "variable",
            "constant",
            "comment",
            "docstring",
            "error",
            "warning",
            "added",
            "removed",
            "text",
            "muted",
        }
        actual_roles = {role.value for role in SyntaxRole}
        assert expected_roles.issubset(actual_roles)


class TestSyntaxPalette:
    """Tests for SyntaxPalette."""

    def test_palette_is_frozen(self) -> None:
        """Palette is immutable."""
        from dataclasses import FrozenInstanceError

        palette = SyntaxPalette(
            name="test",
            background="#000000",
            text="#ffffff",
        )
        with pytest.raises(FrozenInstanceError):
            palette.name = "modified"  # type: ignore

    def test_palette_requires_name(self) -> None:
        """Palette requires a name."""
        with pytest.raises(ValueError, match="name"):
            SyntaxPalette(name="", background="#000000", text="#ffffff")

    def test_palette_requires_background(self) -> None:
        """Palette requires a background color."""
        with pytest.raises(ValueError, match="[Bb]ackground"):
            SyntaxPalette(name="test", background="", text="#ffffff")

    def test_palette_with_defaults(self) -> None:
        """with_defaults fills in missing colors."""
        minimal = SyntaxPalette(
            name="minimal",
            background="#000000",
            text="#ffffff",
        )
        filled = minimal.with_defaults()
        assert filled.control_flow == "#ffffff"  # Falls back to text
        assert filled.string == "#ffffff"

    def test_palette_to_css_vars(self) -> None:
        """to_css_vars generates CSS custom properties."""
        palette = MONOKAI
        css_vars = palette.to_css_vars()
        assert "--syntax-bg:" in css_vars
        assert "--syntax-control:" in css_vars
        assert "--syntax-string:" in css_vars


class TestAdaptivePalette:
    """Tests for AdaptivePalette."""

    def test_adaptive_has_light_dark(self) -> None:
        """Adaptive palette has light and dark variants."""
        assert isinstance(GITHUB.light, SyntaxPalette)
        assert isinstance(GITHUB.dark, SyntaxPalette)
        assert GITHUB.light.name == "github-light"
        assert GITHUB.dark.name == "github-dark"

    def test_adaptive_to_css(self) -> None:
        """to_css generates CSS with light-dark() and fallbacks."""
        css = GITHUB.to_css()
        assert "light-dark(" in css
        assert "@media (prefers-color-scheme: dark)" in css
        assert '[data-theme="dark"]' in css
        assert '[data-theme="light"]' in css


class TestCssGeneration:
    """Tests for CSS generation."""

    def test_generate_css_with_palette(self) -> None:
        """generate_css works with a palette."""
        css = generate_css(MONOKAI)
        assert "/* Generated by Rosettes" in css
        assert "--syntax-bg:" in css
        assert ".rosettes" in css

    def test_generate_css_semantic(self) -> None:
        """Semantic CSS has readable class names."""
        css = generate_css(MONOKAI, css_class_style="semantic")
        assert ".syntax-control" in css
        assert ".syntax-function" in css
        assert ".syntax-string" in css

    def test_generate_css_pygments(self) -> None:
        """Pygments CSS has short class names."""
        css = generate_css(MONOKAI, css_class_style="pygments")
        assert ".highlight .k" in css
        assert ".highlight .nf" in css
        assert ".highlight .s" in css

    def test_generate_css_layer(self) -> None:
        """CSS can use @layer."""
        css = generate_css(MONOKAI, use_layer=True)
        assert "@layer rosettes" in css

    def test_generate_css_no_layer(self) -> None:
        """CSS can omit @layer."""
        css = generate_css(MONOKAI, use_layer=False)
        assert "@layer rosettes" not in css


class TestValidation:
    """Tests for WCAG validation."""

    def test_contrast_ratio(self) -> None:
        """contrast_ratio calculates correct values."""
        # White on black = max contrast
        ratio = contrast_ratio("#ffffff", "#000000")
        assert ratio == pytest.approx(21.0, rel=0.01)

        # Same color = no contrast
        ratio = contrast_ratio("#ffffff", "#ffffff")
        assert ratio == pytest.approx(1.0, rel=0.01)

    def test_validate_palette_monokai(self) -> None:
        """Monokai passes WCAG validation."""
        warnings = validate_palette(MONOKAI)
        # Monokai should pass with few/no warnings
        assert len(warnings) <= 2

    def test_is_dark_palette(self) -> None:
        """is_dark_palette correctly identifies dark themes."""
        assert is_dark_palette(MONOKAI) is True
        assert is_dark_palette(DRACULA) is True
        assert is_dark_palette(GITHUB.dark) is True
        assert is_dark_palette(GITHUB.light) is False


class TestPaletteRegistry:
    """Tests for palette registry."""

    def test_list_palettes(self) -> None:
        """list_palettes returns available palettes."""
        palettes = list_palettes()
        assert "monokai" in palettes
        assert "dracula" in palettes
        assert "github" in palettes
        assert "catppuccin" in palettes
        assert "nord" in palettes
        assert "bengal-tiger" in palettes

    def test_get_palette(self) -> None:
        """get_palette retrieves palettes by name."""
        monokai = get_palette("monokai")
        assert monokai.name == "monokai"

        github = get_palette("github")
        assert isinstance(github, AdaptivePalette)

    def test_get_palette_unknown(self) -> None:
        """get_palette raises for unknown palettes."""
        with pytest.raises(KeyError, match="unknown"):
            get_palette("unknown")

    def test_register_palette(self) -> None:
        """register_palette adds custom palettes."""
        custom = SyntaxPalette(
            name="test-custom",
            background="#111111",
            text="#eeeeee",
            control_flow="#ff0000",
        )
        register_palette(custom)
        retrieved = get_palette("test-custom")
        assert retrieved == custom


class TestBuiltinPalettes:
    """Tests for built-in palettes."""

    @pytest.mark.parametrize(
        "palette",
        [
            MONOKAI,
            DRACULA,
            ONE_DARK,
            BENGAL_TIGER,
        ],
    )
    def test_dark_palette_properties(self, palette: SyntaxPalette) -> None:
        """Dark palettes have correct structure."""
        assert palette.name
        assert palette.background.startswith("#")
        assert palette.text.startswith("#")
        assert is_dark_palette(palette)

    @pytest.mark.parametrize(
        "palette",
        [
            GITHUB,
            CATPPUCCIN,
            NORD,
        ],
    )
    def test_adaptive_palette_properties(self, palette: AdaptivePalette) -> None:
        """Adaptive palettes have light and dark variants."""
        assert palette.name
        assert palette.light.name.endswith("-light") or "latte" in palette.light.name.lower()
        assert palette.dark.name.endswith("-dark") or "mocha" in palette.dark.name.lower()
        assert is_dark_palette(palette.dark)
        assert not is_dark_palette(palette.light)


class TestTerminalPalette:
    """Tests for TerminalPalette."""

    def test_terminal_palette_defaults(self) -> None:
        """TerminalPalette has ANSI defaults."""
        assert TERMINAL_MONOKAI.name == "monokai-terminal"
        assert TERMINAL_MONOKAI.control_flow  # Has a value
        assert TERMINAL_MONOKAI.string

    def test_from_syntax_palette(self) -> None:
        """Can convert SyntaxPalette to TerminalPalette."""
        terminal = TerminalPalette.from_syntax_palette(DRACULA, color_mode="256")
        assert terminal.name == "dracula-terminal-256"
        assert "38;5;" in terminal.control_flow  # 256-color code

    def test_from_syntax_palette_truecolor(self) -> None:
        """Can convert to truecolor TerminalPalette."""
        terminal = TerminalPalette.from_syntax_palette(MONOKAI, color_mode="truecolor")
        assert "38;2;" in terminal.control_flow  # Truecolor code


class TestHighlightIntegration:
    """Integration tests for theming with highlight()."""

    def test_highlight_semantic_default(self) -> None:
        """Default highlight uses semantic classes."""
        html = highlight("def foo(): pass", "python")
        assert '<div class="rosettes">' in html
        assert "syntax-" in html

    def test_highlight_pygments_mode(self) -> None:
        """Pygments mode uses short class names."""
        html = highlight("def foo(): pass", "python", css_class_style="pygments")
        assert '<div class="highlight">' in html
        # Should have pygments class like kd, nf, etc.

    def test_highlight_with_palette(self) -> None:
        """highlight accepts palette parameter."""
        html = highlight("def foo(): pass", "python", palette="monokai")
        assert "rosettes" in html

    def test_highlight_custom_class(self) -> None:
        """Custom css_class overrides default."""
        html = highlight("x = 1", "python", css_class="my-code")
        assert '<div class="my-code">' in html
