# Local Development Environment
# =============================
#
# Configuration overrides for local development.
# Auto-detected when:
#   - No CI/platform env vars present (default)
#   - BENGAL_ENV=local explicitly set
#
# Optimizations for local dev:
#   - Local baseurl (localhost:8000)
#   - Faster builds (less parallelization overhead)
#   - Debugging-friendly settings
#
# Precedence: _default → local → profile → env vars → CLI

site:
  # Use localhost for local development
  baseurl: "http://localhost:8000"
  
  # Disable external link checks (faster builds, no network calls)
  check_external_links: false

build:
  # Disable parallelization for easier debugging
  # (easier to see console output, breakpoints work better)
  parallel: false
  
  # Incremental builds ON (very fast rebuilds during development)
  incremental: true
  
  # Strict mode OFF (allow warnings during development)
  strict_mode: false

features:
  # Disable intensive features for faster dev cycle
  related_pages: false
  
health_check:
  # Less strict checks during development
  enabled: true
  fail_on_error: false
  validators:
    - frontmatter  # Still validate frontmatter
    # Skip link/image checks for speed

markdown:
  highlight:
    # Lighter style for readability during dev
    style: "github-light"

# Development-specific settings
dev:
  # Live reload server
  live_reload: true
  
  # Show detailed errors
  show_errors: true
  
  # Verbose logging
  verbose: false  # Set to true for debugging

