"""Fuzz testing for Patitas parser (Phase 4 of CommonMark compliance RFC).

Tests that the parser never crashes on any input, regardless of content.
Uses Hypothesis to generate random markdown strings and verifies the parser
handles them gracefully.

See: plan/rfc-patitas-commonmark-compliance.md (Phase 4: Fuzz Testing)
"""

from __future__ import annotations

import pytest

from bengal.parsing.backends.patitas import parse

try:
    from hypothesis import given, settings
    from hypothesis import strategies as st
except ImportError:
    pytest.skip("hypothesis not installed", allow_module_level=True)

# Deadline catches ReDoS/slow examples; max_examples comes from CI profile or default.
FUZZ_SETTINGS = settings(deadline=2000)


@pytest.mark.timeout(90)
class TestFuzzNoCrashes:
    """Fuzz tests to ensure parser never crashes."""

    @given(st.text(min_size=1, max_size=1000))
    @settings(FUZZ_SETTINGS)
    def test_no_crashes(self, markdown: str) -> None:
        """Parser never crashes on any input.

        This test generates random markdown strings and verifies the parser
        handles them without raising unexpected exceptions.

        Args:
            markdown: Random markdown string generated by Hypothesis
        """
        try:
            result = parse(markdown)
            # Parser should always return a string (even if empty)
            assert isinstance(result, str)
        except ValueError, SyntaxError:
            # Syntax errors are acceptable - parser can reject invalid syntax
            pass
        except Exception as e:
            # Any other exception is a bug - parser should never crash
            pytest.fail(f"Parser crashed on input {markdown!r}: {e}")

    @given(st.text(min_size=0, max_size=100))
    @settings(FUZZ_SETTINGS)
    def test_empty_and_short_inputs(self, markdown: str) -> None:
        """Parser handles empty and very short inputs."""
        try:
            result = parse(markdown)
            assert isinstance(result, str)
        except Exception as e:
            pytest.fail(f"Parser failed on short input {markdown!r}: {e}")

    @given(st.text(min_size=100, max_size=5000))
    @settings(FUZZ_SETTINGS)
    def test_long_inputs(self, markdown: str) -> None:
        """Parser handles longer inputs without performance issues."""
        try:
            result = parse(markdown)
            assert isinstance(result, str)
        except Exception as e:
            pytest.fail(f"Parser failed on long input: {e}")

    @given(st.text(min_size=1, max_size=500).filter(lambda s: "\0" not in s))
    @settings(FUZZ_SETTINGS)
    def test_unicode_inputs(self, markdown: str) -> None:
        """Parser handles Unicode characters correctly."""
        try:
            result = parse(markdown)
            assert isinstance(result, str)
        except Exception as e:
            pytest.fail(f"Parser failed on Unicode input: {e}")

    @given(
        st.lists(
            st.text(min_size=1, max_size=100),
            min_size=1,
            max_size=50,
        )
    )
    @settings(FUZZ_SETTINGS)
    def test_multiline_inputs(self, lines: list[str]) -> None:
        """Parser handles multi-line inputs."""
        markdown = "\n".join(lines)
        try:
            result = parse(markdown)
            assert isinstance(result, str)
        except Exception as e:
            pytest.fail(f"Parser failed on multi-line input: {e}")
