# Base Site Configuration
# ======================
#
# This file contains fundamental site metadata that rarely changes
# between environments. It's the foundation of your site configuration.
#
# These settings are merged with environment-specific overrides from:
#   - config/environments/<env>.yaml (e.g., local.yaml, production.yaml)
#   - config/profiles/<profile>.yaml (e.g., writer.yaml, dev.yaml)
#
# Precedence: _default → environment → profile → env vars → CLI flags

site:
  # Site identity (override baseurl per environment)
  title: "My Awesome Site"
  author: "Your Name"
  
  # Base URL (override in environments/production.yaml)
  # Local: http://localhost:8000
  # Production: https://yourdomain.com
  baseurl: "https://example.com"
  
  # Site metadata
  description: "A beautiful static site built with Bengal"
  language: "en"
  
  # Social & SEO
  keywords:
    - static site
    - documentation
    - bengal
  
  # Theme configuration
  theme:
    name: "default"
    default_appearance: "system"  # auto, light, dark, system
    default_palette: ""
    
  # Menu configuration (define navigation menus)
  menu:
    main:
      - name: "Home"
        url: "/"
        weight: 1
      - name: "Docs"
        url: "/docs/"
        weight: 2
      - name: "Blog"
        url: "/blog/"
        weight: 3
      - name: "About"
        url: "/about/"
        weight: 4
    
    footer:
      - name: "Privacy"
        url: "/privacy/"
      - name: "Terms"
        url: "/terms/"
  
  # Taxonomies (content classification)
  taxonomies:
    - tags
    - categories
    - series

