[site]
title = "ᓚᘏᗢ Bengal SSG"
baseurl = "https://example.com"
description = "A quick start example for Bengal SSG"
theme = "default"
author = "Bengal Team"

[build]
output_dir = "public"
parallel = true
incremental = false
max_workers = 10  # 11 CPUs - 1 for OS
markdown_engine = "mistune"  # Options: "python-markdown", "mistune" (faster with custom plugins)

[assets]
minify = true
optimize = true
fingerprint = true

[features]
generate_sitemap = true
generate_rss = true
validate_links = true

# Custom output formats for search, AI discovery, programmatic access
[output_formats]
enabled = true
per_page = ["json", "llm_txt"]  # Generate .json and .txt for each page
site_wide = ["index_json", "llm_full"]  # Generate site-wide index.json and llm-full.txt

[output_formats.options]
include_html_content = true
include_plain_text = true
excerpt_length = 200
exclude_sections = []  # Add sections to exclude, e.g. ["admin", "private"]
exclude_patterns = ["404.html", "search.html"]
json_indent = 2  # Pretty-print JSON (use null/false for compact)
llm_separator_width = 80

[pagination]
items_per_page = 5

# Main navigation menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 3

[[menu.main]]
name = "Docs"
url = "/docs/"
weight = 4
identifier = "docs"

# Nested under Docs
[[menu.main]]
name = "Getting Started"
url = "/docs/"
weight = 1
parent = "docs"

[[menu.main]]
name = "Advanced Topics"
url = "/docs/advanced-markdown/"
weight = 2
parent = "docs"

[[menu.main]]
name = "Tutorials"
url = "/tutorials/"
weight = 5

# Footer menu
[[menu.footer]]
name = "About"
url = "/about/"

[[menu.footer]]
name = "RSS"
url = "/rss.xml"

[[menu.footer]]
name = "Tags"
url = "/tags/"

